<?xml version="1.0" standalone="yes"?>

<!DOCTYPE document [
        <!ELEMENT document (employee)*>
        <!ELEMENT employee (name, hiredate, projects)>
        <!ELEMENT name (firstname, lastname)>
        <!ELEMENT lastname (#PCDATA)>
        <!ELEMENT firstname (#PCDATA)>
        <!ELEMENT hiredate (#PCDATA)>
        <!ELEMENT projects (project)*>
        <!ELEMENT project (product, id, price)>
        <!ELEMENT product (#PCDATA)>
        <!ELEMENT id (#PCDATA)>
        <!ELEMENT price (#PCDATA)>
     ]>
<document>
    <employee>
        <name>
            <firstname>Kelly</firstname>
            <lastname>Grace</lastname>
        </name>
        <hiredate>October, 25, 2005</hiredate>
        <projects>
            <project>
                <product>Printer</product>
                <id>111</id>
                <price>$111.00</price>
            </project>
            <project>
            <product>Laptop</product>
            <id>222</id>
            <price>$989.00</price>
        </project>
        </projects>
    </employee>
</document>